language: ruby
bundler_args: --without doc
rvm:
  - "2.5"
  - "2.6"
  - "2.7"
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  email:
    - github@elskwid.net
